---
project_name: cicd

builds:
  - main: ./cmd/playground
    binary: playground
    ldflags:
      - -s -w
      - -X github.com/calmonr/cicd/pkg/version.version={{.Version}}
      - -X github.com/calmonr/cicd/pkg/version.commit={{.Commit}}
      - -X github.com/calmonr/cicd/pkg/version.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

checksum:
  name_template: checksums.txt

changelog:
  use: github-native

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - &amd_image_gh ghcr.io/calmonr/cicd:v{{ .Version }}-amd64
      - &amd_image_dh calmonr/cicd:v{{ .Version }}-amd64
    dockerfile: &dockerfile Dockerfile.release
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
  - goos: linux
    goarch: arm64
    image_templates:
      - &arm_image_gh ghcr.io/calmonr/cicd:v{{ .Version }}-arm64
      - &arm_image_dh calmonr/cicd:v{{ .Version }}-arm64
    dockerfile: *dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64

docker_manifests:
  - name_template: ghcr.io/calmonr/cicd:v{{ .Version }}
    image_templates:
      - *amd_image_gh
      - *arm_image_gh
  - name_template: ghcr.io/calmonr/cicd:latest
    image_templates:
      - *amd_image_gh
      - *arm_image_gh
  - name_template: calmonr/cicd:v{{ .Version }}
    image_templates:
      - *amd_image_dh
      - *arm_image_dh
  - name_template: calmonr/cicd:latest
    image_templates:
      - *amd_image_dh
      - *arm_image_dh
